# Generated by Django 4.2.1 on 2023-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_goal_is_achieved_alter_qa_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='question',
        ),
        migrations.AddField(
            model_name='qa',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
