# Generated by Django 4.2.1 on 2023-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_diary_monthanddate_remove_goal_monthanddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='finished_at',
        ),
    ]
