# Generated by Django 4.2.1 on 2023-05-14 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_date_d_alter_diary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_date', to='diary.date'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_date', to='diary.date'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='created_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_date', to='diary.date'),
        ),
    ]
